export interface Fabryka {
  MACHINE: string;
  DATETIME_FROM: string;
  DATETIME_TO: Date;
  H0: number;
  H1: number;
  H2: number;
  H3: number;
  H4: number;
  H5: number;
  H6: number;
  H7: number;
  H8: number;
  H9: number;
  H10: number;
  H11: number;
  H12: number;
  H13: number;
  H14: number;
  H15: number;
  H16: number;
  H17: number;
  H18: number;
  H19: number;
  H20: number;
  H21: number;
  H22: number;
  H23: number;
  SCRAP_PERCENTAGE: number;
  DOWNTIME_PERCENTAGE:number;
  PRODUCTION:number;
}